version: "3.7"

services:
  backend:
    image: node:latest
    command: sh -c "cd .\backend\ && npm install && npm run dev"
    ports:
      - 8080:8080
    working_dir: ./backend
    volumes:
      - ./:/backend
  frontend:
    image: nginx:latest
    ports:
      - 81:80
      working_dir: ./frontend
      volumes:
        - ./:/frontend
